name: model_a
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'


dependency_overrides:
  mhu_dart_sourcegen:
    path: ../../../mhu_dart_sourcegen
  mhu_dart_commons:
    path: ../../../mhu_dart_commons
  mhu_dart_proto:
    path: ../../../mhu_dart_proto
  mhu_dart_annotation:
    path: ../../../mhu_dart_annotation

dependencies:
  protobuf: ^3.0.0
  fixnum: ^1.1.0
  collection: ^1.17.2
  mhu_dart_proto: ^1.0.1
  mhu_dart_commons: ^1.0.7


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mhu_dart_pbgen:
    path: ../..

